--
-- Custom fields system (Phase 3.1)
-- Admin-definable fields attached to contacts AND deals.
-- Plus attachments jsonb columns for arbitrary file references.
--

create table public.custom_field_definitions (
    id bigint generated by default as identity primary key,
    entity_type text not null,
    field_key text not null,
    label text not null,
    field_type text not null,
    options jsonb not null default '{}'::jsonb,
    display_order integer not null default 0,
    active boolean not null default true,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint custom_field_definitions_entity_type_check
        check (entity_type in ('contact', 'deal')),
    constraint custom_field_definitions_field_type_check
        check (field_type in ('text', 'number', 'boolean', 'date', 'url', 'select', 'textarea'))
);

alter table public.custom_field_definitions
    add constraint custom_field_definitions_sales_id_fkey
        foreign key (sales_id) references public.sales(id);

-- field_key must be unique per entity_type (e.g. you can't have two 'pool_depth_feet' fields on contacts)
create unique index custom_field_definitions_entity_key_idx
    on public.custom_field_definitions (entity_type, field_key);

create index custom_field_definitions_entity_active_order_idx
    on public.custom_field_definitions (entity_type, active, display_order);

-- Sparse values + attachments on contacts
alter table public.contacts
    add column custom_fields jsonb not null default '{}'::jsonb,
    add column attachments jsonb not null default '[]'::jsonb;

-- Same on deals
alter table public.deals
    add column custom_fields jsonb not null default '{}'::jsonb,
    add column attachments jsonb not null default '[]'::jsonb;

-- RLS
alter table public.custom_field_definitions enable row level security;

create policy "Enable read access for authenticated users"
    on public.custom_field_definitions for select to authenticated using (true);
create policy "Enable insert for admins"
    on public.custom_field_definitions for insert to authenticated
    with check (public.is_admin());
create policy "Enable update for admins"
    on public.custom_field_definitions for update to authenticated
    using (public.is_admin()) with check (public.is_admin());
create policy "Enable delete for admins"
    on public.custom_field_definitions for delete to authenticated
    using (public.is_admin());

-- Grants
grant all on table public.custom_field_definitions to anon;
grant all on table public.custom_field_definitions to authenticated;
grant all on table public.custom_field_definitions to service_role;

grant all on sequence public.custom_field_definitions_id_seq to anon;
grant all on sequence public.custom_field_definitions_id_seq to authenticated;
grant all on sequence public.custom_field_definitions_id_seq to service_role;

-- Auto-set sales_id = current user on insert
create or replace trigger set_custom_field_definitions_sales_id_trigger
    before insert on public.custom_field_definitions
    for each row execute function public.set_sales_id_default();
