--
-- Lifeguards roster (workforce records, do not log in)
-- Supervisor on deals (polymorphic: from sales OR from lifeguards)
-- Deal-lifeguard allocation with swap history
--

create table public.lifeguards (
    id bigint generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    email extensions.citext,
    phone text,
    hourly_rate_cents integer,
    certifications jsonb not null default '[]'::jsonb,
    regions text[] not null default '{}'::text[],
    active boolean not null default true,
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.lifeguards
    add constraint lifeguards_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index lifeguards_active_idx on public.lifeguards using btree (active);

-- Two nullable FKs + check: a deal can have a supervisor from sales OR lifeguards (not both).
alter table public.deals
    add column supervisor_sales_id bigint,
    add column supervisor_lifeguard_id bigint;

alter table public.deals
    add constraint deals_supervisor_sales_id_fkey foreign key (supervisor_sales_id) references public.sales(id),
    add constraint deals_supervisor_lifeguard_id_fkey foreign key (supervisor_lifeguard_id) references public.lifeguards(id),
    add constraint deals_one_supervisor_check check (
        not (supervisor_sales_id is not null and supervisor_lifeguard_id is not null)
    );

create index deals_supervisor_sales_id_idx on public.deals using btree (supervisor_sales_id);
create index deals_supervisor_lifeguard_id_idx on public.deals using btree (supervisor_lifeguard_id);

-- Many lifeguards per deal. Swappable: replacing keeps history (status='replaced', replaced_by).
create table public.deal_lifeguards (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    lifeguard_id bigint not null,
    status text not null default 'proposed',
    is_primary boolean not null default false,
    assigned_at timestamp with time zone not null default now(),
    replaced_at timestamp with time zone,
    replaced_by bigint,
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.deal_lifeguards
    add constraint deal_lifeguards_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade,
    add constraint deal_lifeguards_lifeguard_id_fkey foreign key (lifeguard_id) references public.lifeguards(id) on update cascade on delete restrict,
    add constraint deal_lifeguards_replaced_by_fkey foreign key (replaced_by) references public.lifeguards(id),
    add constraint deal_lifeguards_sales_id_fkey foreign key (sales_id) references public.sales(id),
    add constraint deal_lifeguards_status_check check (status in ('proposed', 'confirmed', 'on_site', 'declined', 'replaced'));

create index deal_lifeguards_deal_id_idx on public.deal_lifeguards using btree (deal_id);
create index deal_lifeguards_lifeguard_id_idx on public.deal_lifeguards using btree (lifeguard_id);

-- RLS: same pattern as the rest of the app (authenticated users full access)
alter table public.lifeguards enable row level security;
alter table public.deal_lifeguards enable row level security;

create policy "Enable read access for authenticated users" on public.lifeguards for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.lifeguards for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.lifeguards for update to authenticated using (true) with check (true);
create policy "Lifeguards Delete Policy" on public.lifeguards for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.deal_lifeguards for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.deal_lifeguards for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.deal_lifeguards for update to authenticated using (true) with check (true);
create policy "Deal Lifeguards Delete Policy" on public.deal_lifeguards for delete to authenticated using (true);

-- Grants (mirror the pattern in 06_grants.sql)
grant all on table public.lifeguards to anon;
grant all on table public.lifeguards to authenticated;
grant all on table public.lifeguards to service_role;

grant all on table public.deal_lifeguards to anon;
grant all on table public.deal_lifeguards to authenticated;
grant all on table public.deal_lifeguards to service_role;

grant all on sequence public.lifeguards_id_seq to anon;
grant all on sequence public.lifeguards_id_seq to authenticated;
grant all on sequence public.lifeguards_id_seq to service_role;

grant all on sequence public.deal_lifeguards_id_seq to anon;
grant all on sequence public.deal_lifeguards_id_seq to authenticated;
grant all on sequence public.deal_lifeguards_id_seq to service_role;

-- Auto-set sales_id = current user on insert (same trigger used by other tables)
create or replace trigger set_lifeguard_sales_id_trigger
    before insert on public.lifeguards
    for each row execute function public.set_sales_id_default();

create or replace trigger set_deal_lifeguard_sales_id_trigger
    before insert on public.deal_lifeguards
    for each row execute function public.set_sales_id_default();
